#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autos_SCC.DomainModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AAP_Autos")]
	public partial class AAPDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbc_MarcaAuto(tbc_MarcaAuto instance);
    partial void Updatetbc_MarcaAuto(tbc_MarcaAuto instance);
    partial void Deletetbc_MarcaAuto(tbc_MarcaAuto instance);
    partial void Inserttbc_Sucursales(tbc_Sucursales instance);
    partial void Updatetbc_Sucursales(tbc_Sucursales instance);
    partial void Deletetbc_Sucursales(tbc_Sucursales instance);
    partial void Inserttbc_StatusAuto(tbc_StatusAuto instance);
    partial void Updatetbc_StatusAuto(tbc_StatusAuto instance);
    partial void Deletetbc_StatusAuto(tbc_StatusAuto instance);
    partial void Inserttbc_Version(tbc_Version instance);
    partial void Updatetbc_Version(tbc_Version instance);
    partial void Deletetbc_Version(tbc_Version instance);
    partial void Inserttbc_TipoAuto(tbc_TipoAuto instance);
    partial void Updatetbc_TipoAuto(tbc_TipoAuto instance);
    partial void Deletetbc_TipoAuto(tbc_TipoAuto instance);
    partial void Inserttbr_GastosAuto(tbr_GastosAuto instance);
    partial void Updatetbr_GastosAuto(tbr_GastosAuto instance);
    partial void Deletetbr_GastosAuto(tbr_GastosAuto instance);
    partial void Inserttbc_Plazo(tbc_Plazo instance);
    partial void Updatetbc_Plazo(tbc_Plazo instance);
    partial void Deletetbc_Plazo(tbc_Plazo instance);
    #endregion
		
		public AAPDataContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SqlDefault"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AAPDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AAPDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AAPDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AAPDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbc_MarcaAuto> tbc_MarcaAuto
		{
			get
			{
				return this.GetTable<tbc_MarcaAuto>();
			}
		}
		
		public System.Data.Linq.Table<tbc_Sucursales> tbc_Sucursales
		{
			get
			{
				return this.GetTable<tbc_Sucursales>();
			}
		}
		
		public System.Data.Linq.Table<tbc_StatusAuto> tbc_StatusAuto
		{
			get
			{
				return this.GetTable<tbc_StatusAuto>();
			}
		}
		
		public System.Data.Linq.Table<tbc_Version> tbc_Version
		{
			get
			{
				return this.GetTable<tbc_Version>();
			}
		}
		
		public System.Data.Linq.Table<tbc_TipoAuto> tbc_TipoAuto
		{
			get
			{
				return this.GetTable<tbc_TipoAuto>();
			}
		}
		
		public System.Data.Linq.Table<tbr_GastosAuto> tbr_GastosAuto
		{
			get
			{
				return this.GetTable<tbr_GastosAuto>();
			}
		}
		
		public System.Data.Linq.Table<tbc_Plazo> tbc_Plazo
		{
			get
			{
				return this.GetTable<tbc_Plazo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Catalogos.tbc_MarcaAuto")]
	public partial class tbc_MarcaAuto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fi_Id;
		
		private string _fc_Descripcion;
		
		private int _fi_Activo;
		
		private string _fc_Usuario;
		
		private System.DateTime _fd_FechaUltMovimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfi_IdChanging(int value);
    partial void Onfi_IdChanged();
    partial void Onfc_DescripcionChanging(string value);
    partial void Onfc_DescripcionChanged();
    partial void Onfi_ActivoChanging(int value);
    partial void Onfi_ActivoChanged();
    partial void Onfc_UsuarioChanging(string value);
    partial void Onfc_UsuarioChanged();
    partial void Onfd_FechaUltMovimientoChanging(System.DateTime value);
    partial void Onfd_FechaUltMovimientoChanged();
    #endregion
		
		public tbc_MarcaAuto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fi_Id
		{
			get
			{
				return this._fi_Id;
			}
			set
			{
				if ((this._fi_Id != value))
				{
					this.Onfi_IdChanging(value);
					this.SendPropertyChanging();
					this._fi_Id = value;
					this.SendPropertyChanged("fi_Id");
					this.Onfi_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fc_Descripcion
		{
			get
			{
				return this._fc_Descripcion;
			}
			set
			{
				if ((this._fc_Descripcion != value))
				{
					this.Onfc_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._fc_Descripcion = value;
					this.SendPropertyChanged("fc_Descripcion");
					this.Onfc_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Activo", DbType="Int NOT NULL")]
		public int fi_Activo
		{
			get
			{
				return this._fi_Activo;
			}
			set
			{
				if ((this._fi_Activo != value))
				{
					this.Onfi_ActivoChanging(value);
					this.SendPropertyChanging();
					this._fi_Activo = value;
					this.SendPropertyChanged("fi_Activo");
					this.Onfi_ActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fc_Usuario
		{
			get
			{
				return this._fc_Usuario;
			}
			set
			{
				if ((this._fc_Usuario != value))
				{
					this.Onfc_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._fc_Usuario = value;
					this.SendPropertyChanged("fc_Usuario");
					this.Onfc_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd_FechaUltMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fd_FechaUltMovimiento
		{
			get
			{
				return this._fd_FechaUltMovimiento;
			}
			set
			{
				if ((this._fd_FechaUltMovimiento != value))
				{
					this.Onfd_FechaUltMovimientoChanging(value);
					this.SendPropertyChanging();
					this._fd_FechaUltMovimiento = value;
					this.SendPropertyChanged("fd_FechaUltMovimiento");
					this.Onfd_FechaUltMovimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Autos.tbc_Sucursales")]
	public partial class tbc_Sucursales : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fi_Id;
		
		private string _fc_Descripcion;
		
		private int _fi_Activo;
		
		private string _fc_Usuario;
		
		private System.DateTime _fd_FechaUltMovimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfi_IdChanging(int value);
    partial void Onfi_IdChanged();
    partial void Onfc_DescripcionChanging(string value);
    partial void Onfc_DescripcionChanged();
    partial void Onfi_ActivoChanging(int value);
    partial void Onfi_ActivoChanged();
    partial void Onfc_UsuarioChanging(string value);
    partial void Onfc_UsuarioChanged();
    partial void Onfd_FechaUltMovimientoChanging(System.DateTime value);
    partial void Onfd_FechaUltMovimientoChanged();
    #endregion
		
		public tbc_Sucursales()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fi_Id
		{
			get
			{
				return this._fi_Id;
			}
			set
			{
				if ((this._fi_Id != value))
				{
					this.Onfi_IdChanging(value);
					this.SendPropertyChanging();
					this._fi_Id = value;
					this.SendPropertyChanged("fi_Id");
					this.Onfi_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fc_Descripcion
		{
			get
			{
				return this._fc_Descripcion;
			}
			set
			{
				if ((this._fc_Descripcion != value))
				{
					this.Onfc_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._fc_Descripcion = value;
					this.SendPropertyChanged("fc_Descripcion");
					this.Onfc_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Activo", DbType="Int NOT NULL")]
		public int fi_Activo
		{
			get
			{
				return this._fi_Activo;
			}
			set
			{
				if ((this._fi_Activo != value))
				{
					this.Onfi_ActivoChanging(value);
					this.SendPropertyChanging();
					this._fi_Activo = value;
					this.SendPropertyChanged("fi_Activo");
					this.Onfi_ActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fc_Usuario
		{
			get
			{
				return this._fc_Usuario;
			}
			set
			{
				if ((this._fc_Usuario != value))
				{
					this.Onfc_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._fc_Usuario = value;
					this.SendPropertyChanged("fc_Usuario");
					this.Onfc_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd_FechaUltMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fd_FechaUltMovimiento
		{
			get
			{
				return this._fd_FechaUltMovimiento;
			}
			set
			{
				if ((this._fd_FechaUltMovimiento != value))
				{
					this.Onfd_FechaUltMovimientoChanging(value);
					this.SendPropertyChanging();
					this._fd_FechaUltMovimiento = value;
					this.SendPropertyChanged("fd_FechaUltMovimiento");
					this.Onfd_FechaUltMovimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Catalogos.tbc_StatusAuto")]
	public partial class tbc_StatusAuto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fi_Id;
		
		private string _fc_Descripcion;
		
		private int _fi_Activo;
		
		private string _fc_Usuario;
		
		private System.DateTime _fd_FechaUltMovimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfi_IdChanging(int value);
    partial void Onfi_IdChanged();
    partial void Onfc_DescripcionChanging(string value);
    partial void Onfc_DescripcionChanged();
    partial void Onfi_ActivoChanging(int value);
    partial void Onfi_ActivoChanged();
    partial void Onfc_UsuarioChanging(string value);
    partial void Onfc_UsuarioChanged();
    partial void Onfd_FechaUltMovimientoChanging(System.DateTime value);
    partial void Onfd_FechaUltMovimientoChanged();
    #endregion
		
		public tbc_StatusAuto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fi_Id
		{
			get
			{
				return this._fi_Id;
			}
			set
			{
				if ((this._fi_Id != value))
				{
					this.Onfi_IdChanging(value);
					this.SendPropertyChanging();
					this._fi_Id = value;
					this.SendPropertyChanged("fi_Id");
					this.Onfi_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fc_Descripcion
		{
			get
			{
				return this._fc_Descripcion;
			}
			set
			{
				if ((this._fc_Descripcion != value))
				{
					this.Onfc_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._fc_Descripcion = value;
					this.SendPropertyChanged("fc_Descripcion");
					this.Onfc_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Activo", DbType="Int NOT NULL")]
		public int fi_Activo
		{
			get
			{
				return this._fi_Activo;
			}
			set
			{
				if ((this._fi_Activo != value))
				{
					this.Onfi_ActivoChanging(value);
					this.SendPropertyChanging();
					this._fi_Activo = value;
					this.SendPropertyChanged("fi_Activo");
					this.Onfi_ActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fc_Usuario
		{
			get
			{
				return this._fc_Usuario;
			}
			set
			{
				if ((this._fc_Usuario != value))
				{
					this.Onfc_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._fc_Usuario = value;
					this.SendPropertyChanged("fc_Usuario");
					this.Onfc_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd_FechaUltMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fd_FechaUltMovimiento
		{
			get
			{
				return this._fd_FechaUltMovimiento;
			}
			set
			{
				if ((this._fd_FechaUltMovimiento != value))
				{
					this.Onfd_FechaUltMovimientoChanging(value);
					this.SendPropertyChanging();
					this._fd_FechaUltMovimiento = value;
					this.SendPropertyChanged("fd_FechaUltMovimiento");
					this.Onfd_FechaUltMovimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Catalogos.tbc_Version")]
	public partial class tbc_Version : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fi_Id;
		
		private int _fi_IdTipoAuto;
		
		private string _fc_Descripcion;
		
		private int _fi_Activo;
		
		private string _fc_Usuario;
		
		private System.DateTime _fd_FechaUltMovimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfi_IdChanging(int value);
    partial void Onfi_IdChanged();
    partial void Onfi_IdTipoAutoChanging(int value);
    partial void Onfi_IdTipoAutoChanged();
    partial void Onfc_DescripcionChanging(string value);
    partial void Onfc_DescripcionChanged();
    partial void Onfi_ActivoChanging(int value);
    partial void Onfi_ActivoChanged();
    partial void Onfc_UsuarioChanging(string value);
    partial void Onfc_UsuarioChanged();
    partial void Onfd_FechaUltMovimientoChanging(System.DateTime value);
    partial void Onfd_FechaUltMovimientoChanged();
    #endregion
		
		public tbc_Version()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fi_Id
		{
			get
			{
				return this._fi_Id;
			}
			set
			{
				if ((this._fi_Id != value))
				{
					this.Onfi_IdChanging(value);
					this.SendPropertyChanging();
					this._fi_Id = value;
					this.SendPropertyChanged("fi_Id");
					this.Onfi_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_IdTipoAuto", DbType="Int NOT NULL")]
		public int fi_IdTipoAuto
		{
			get
			{
				return this._fi_IdTipoAuto;
			}
			set
			{
				if ((this._fi_IdTipoAuto != value))
				{
					this.Onfi_IdTipoAutoChanging(value);
					this.SendPropertyChanging();
					this._fi_IdTipoAuto = value;
					this.SendPropertyChanged("fi_IdTipoAuto");
					this.Onfi_IdTipoAutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fc_Descripcion
		{
			get
			{
				return this._fc_Descripcion;
			}
			set
			{
				if ((this._fc_Descripcion != value))
				{
					this.Onfc_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._fc_Descripcion = value;
					this.SendPropertyChanged("fc_Descripcion");
					this.Onfc_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Activo", DbType="Int NOT NULL")]
		public int fi_Activo
		{
			get
			{
				return this._fi_Activo;
			}
			set
			{
				if ((this._fi_Activo != value))
				{
					this.Onfi_ActivoChanging(value);
					this.SendPropertyChanging();
					this._fi_Activo = value;
					this.SendPropertyChanged("fi_Activo");
					this.Onfi_ActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fc_Usuario
		{
			get
			{
				return this._fc_Usuario;
			}
			set
			{
				if ((this._fc_Usuario != value))
				{
					this.Onfc_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._fc_Usuario = value;
					this.SendPropertyChanged("fc_Usuario");
					this.Onfc_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd_FechaUltMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fd_FechaUltMovimiento
		{
			get
			{
				return this._fd_FechaUltMovimiento;
			}
			set
			{
				if ((this._fd_FechaUltMovimiento != value))
				{
					this.Onfd_FechaUltMovimientoChanging(value);
					this.SendPropertyChanging();
					this._fd_FechaUltMovimiento = value;
					this.SendPropertyChanged("fd_FechaUltMovimiento");
					this.Onfd_FechaUltMovimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Catalogos.tbc_TipoAuto")]
	public partial class tbc_TipoAuto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fi_Id;
		
		private int _fi_IdMarca;
		
		private string _fc_Descripcion;
		
		private int _fi_Activo;
		
		private string _fc_Usuario;
		
		private System.DateTime _fd_FechaUltMovimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfi_IdChanging(int value);
    partial void Onfi_IdChanged();
    partial void Onfi_IdMarcaChanging(int value);
    partial void Onfi_IdMarcaChanged();
    partial void Onfc_DescripcionChanging(string value);
    partial void Onfc_DescripcionChanged();
    partial void Onfi_ActivoChanging(int value);
    partial void Onfi_ActivoChanged();
    partial void Onfc_UsuarioChanging(string value);
    partial void Onfc_UsuarioChanged();
    partial void Onfd_FechaUltMovimientoChanging(System.DateTime value);
    partial void Onfd_FechaUltMovimientoChanged();
    #endregion
		
		public tbc_TipoAuto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fi_Id
		{
			get
			{
				return this._fi_Id;
			}
			set
			{
				if ((this._fi_Id != value))
				{
					this.Onfi_IdChanging(value);
					this.SendPropertyChanging();
					this._fi_Id = value;
					this.SendPropertyChanged("fi_Id");
					this.Onfi_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_IdMarca", DbType="Int NOT NULL")]
		public int fi_IdMarca
		{
			get
			{
				return this._fi_IdMarca;
			}
			set
			{
				if ((this._fi_IdMarca != value))
				{
					this.Onfi_IdMarcaChanging(value);
					this.SendPropertyChanging();
					this._fi_IdMarca = value;
					this.SendPropertyChanged("fi_IdMarca");
					this.Onfi_IdMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fc_Descripcion
		{
			get
			{
				return this._fc_Descripcion;
			}
			set
			{
				if ((this._fc_Descripcion != value))
				{
					this.Onfc_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._fc_Descripcion = value;
					this.SendPropertyChanged("fc_Descripcion");
					this.Onfc_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Activo", DbType="Int NOT NULL")]
		public int fi_Activo
		{
			get
			{
				return this._fi_Activo;
			}
			set
			{
				if ((this._fi_Activo != value))
				{
					this.Onfi_ActivoChanging(value);
					this.SendPropertyChanging();
					this._fi_Activo = value;
					this.SendPropertyChanged("fi_Activo");
					this.Onfi_ActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fc_Usuario
		{
			get
			{
				return this._fc_Usuario;
			}
			set
			{
				if ((this._fc_Usuario != value))
				{
					this.Onfc_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._fc_Usuario = value;
					this.SendPropertyChanged("fc_Usuario");
					this.Onfc_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd_FechaUltMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fd_FechaUltMovimiento
		{
			get
			{
				return this._fd_FechaUltMovimiento;
			}
			set
			{
				if ((this._fd_FechaUltMovimiento != value))
				{
					this.Onfd_FechaUltMovimientoChanging(value);
					this.SendPropertyChanging();
					this._fd_FechaUltMovimiento = value;
					this.SendPropertyChanged("fd_FechaUltMovimiento");
					this.Onfd_FechaUltMovimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Catalogos.tbr_GastosAuto")]
	public partial class tbr_GastosAuto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fi_Id;
		
		private int _fi_IdAuto;
		
		private string _fc_Descripcion;
		
		private decimal _fm_Monto;
		
		private string _fc_Usuario;
		
		private System.DateTime _fd_FechaUltMovimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfi_IdChanging(int value);
    partial void Onfi_IdChanged();
    partial void Onfi_IdAutoChanging(int value);
    partial void Onfi_IdAutoChanged();
    partial void Onfc_DescripcionChanging(string value);
    partial void Onfc_DescripcionChanged();
    partial void Onfm_MontoChanging(decimal value);
    partial void Onfm_MontoChanged();
    partial void Onfc_UsuarioChanging(string value);
    partial void Onfc_UsuarioChanged();
    partial void Onfd_FechaUltMovimientoChanging(System.DateTime value);
    partial void Onfd_FechaUltMovimientoChanged();
    #endregion
		
		public tbr_GastosAuto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fi_Id
		{
			get
			{
				return this._fi_Id;
			}
			set
			{
				if ((this._fi_Id != value))
				{
					this.Onfi_IdChanging(value);
					this.SendPropertyChanging();
					this._fi_Id = value;
					this.SendPropertyChanged("fi_Id");
					this.Onfi_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_IdAuto", DbType="Int NOT NULL")]
		public int fi_IdAuto
		{
			get
			{
				return this._fi_IdAuto;
			}
			set
			{
				if ((this._fi_IdAuto != value))
				{
					this.Onfi_IdAutoChanging(value);
					this.SendPropertyChanging();
					this._fi_IdAuto = value;
					this.SendPropertyChanged("fi_IdAuto");
					this.Onfi_IdAutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fc_Descripcion
		{
			get
			{
				return this._fc_Descripcion;
			}
			set
			{
				if ((this._fc_Descripcion != value))
				{
					this.Onfc_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._fc_Descripcion = value;
					this.SendPropertyChanged("fc_Descripcion");
					this.Onfc_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fm_Monto", DbType="Money NOT NULL")]
		public decimal fm_Monto
		{
			get
			{
				return this._fm_Monto;
			}
			set
			{
				if ((this._fm_Monto != value))
				{
					this.Onfm_MontoChanging(value);
					this.SendPropertyChanging();
					this._fm_Monto = value;
					this.SendPropertyChanged("fm_Monto");
					this.Onfm_MontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fc_Usuario
		{
			get
			{
				return this._fc_Usuario;
			}
			set
			{
				if ((this._fc_Usuario != value))
				{
					this.Onfc_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._fc_Usuario = value;
					this.SendPropertyChanged("fc_Usuario");
					this.Onfc_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd_FechaUltMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fd_FechaUltMovimiento
		{
			get
			{
				return this._fd_FechaUltMovimiento;
			}
			set
			{
				if ((this._fd_FechaUltMovimiento != value))
				{
					this.Onfd_FechaUltMovimientoChanging(value);
					this.SendPropertyChanging();
					this._fd_FechaUltMovimiento = value;
					this.SendPropertyChanged("fd_FechaUltMovimiento");
					this.Onfd_FechaUltMovimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Catalogos.tbc_Plazo")]
	public partial class tbc_Plazo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fi_Id;
		
		private string _fc_Descripcion;
		
		private int _fi_Activo;
		
		private string _fc_Usuario;
		
		private System.DateTime _fd_FechaUltMovimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfi_IdChanging(int value);
    partial void Onfi_IdChanged();
    partial void Onfc_DescripcionChanging(string value);
    partial void Onfc_DescripcionChanged();
    partial void Onfi_ActivoChanging(int value);
    partial void Onfi_ActivoChanged();
    partial void Onfc_UsuarioChanging(string value);
    partial void Onfc_UsuarioChanged();
    partial void Onfd_FechaUltMovimientoChanging(System.DateTime value);
    partial void Onfd_FechaUltMovimientoChanged();
    #endregion
		
		public tbc_Plazo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fi_Id
		{
			get
			{
				return this._fi_Id;
			}
			set
			{
				if ((this._fi_Id != value))
				{
					this.Onfi_IdChanging(value);
					this.SendPropertyChanging();
					this._fi_Id = value;
					this.SendPropertyChanged("fi_Id");
					this.Onfi_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fc_Descripcion
		{
			get
			{
				return this._fc_Descripcion;
			}
			set
			{
				if ((this._fc_Descripcion != value))
				{
					this.Onfc_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._fc_Descripcion = value;
					this.SendPropertyChanged("fc_Descripcion");
					this.Onfc_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fi_Activo", DbType="Int NOT NULL")]
		public int fi_Activo
		{
			get
			{
				return this._fi_Activo;
			}
			set
			{
				if ((this._fi_Activo != value))
				{
					this.Onfi_ActivoChanging(value);
					this.SendPropertyChanging();
					this._fi_Activo = value;
					this.SendPropertyChanged("fi_Activo");
					this.Onfi_ActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fc_Usuario
		{
			get
			{
				return this._fc_Usuario;
			}
			set
			{
				if ((this._fc_Usuario != value))
				{
					this.Onfc_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._fc_Usuario = value;
					this.SendPropertyChanged("fc_Usuario");
					this.Onfc_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd_FechaUltMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fd_FechaUltMovimiento
		{
			get
			{
				return this._fd_FechaUltMovimiento;
			}
			set
			{
				if ((this._fd_FechaUltMovimiento != value))
				{
					this.Onfd_FechaUltMovimientoChanging(value);
					this.SendPropertyChanging();
					this._fd_FechaUltMovimiento = value;
					this.SendPropertyChanged("fd_FechaUltMovimiento");
					this.Onfd_FechaUltMovimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
