<?xml version="1.0" encoding="utf-8"?><Database Name="AAP_Autos" Class="AAPDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-QVLQVTGV;Initial Catalog=AAP_Autos;Integrated Security=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SqlDefault" Provider="System.Data.SqlClient" />
  <Table Name="Catalogos.tbc_MarcaAuto" Member="tbc_MarcaAuto">
    <Type Name="tbc_MarcaAuto">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fi_Activo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Autos.tbc_Sucursales" Member="tbc_Sucursales">
    <Type Name="tbc_Sucursales">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fi_Activo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Catalogos.tbc_StatusAuto" Member="tbc_StatusAuto">
    <Type Name="tbc_StatusAuto">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fi_Activo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Catalogos.tbc_Version" Member="tbc_Version">
    <Type Name="tbc_Version">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fi_IdTipoAuto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fi_Activo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Catalogos.tbc_TipoAuto" Member="tbc_TipoAuto">
    <Type Name="tbc_TipoAuto">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fi_IdMarca" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fi_Activo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Catalogos.tbr_GastosAuto" Member="tbr_GastosAuto">
    <Type Name="tbr_GastosAuto">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fi_IdAuto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fm_Monto" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Catalogos.tbc_Plazo" Member="tbc_Plazo">
    <Type Name="tbc_Plazo">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fi_Activo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Catalogos.tbc_TipoFacturas" Member="tbc_TipoFacturas">
    <Type Name="tbc_TipoFacturas">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fi_Activo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Catalogos.tbc_TipoTransmision" Member="tbc_TipoTransmision">
    <Type Name="tbc_TipoTransmision">
      <Column Name="fi_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fc_Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fi_Activo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fc_Usuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fd_FechaUltMovimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>